### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by sgacio** [sgacio/assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [ ] Portfolio link

## Summary
- [x] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [x] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [x] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [x] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [ ] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by sgacio** [comment]
https://docs.google.com/document/d/1X1aq3tL7W-1vV5sqA5WZolRDIN3BLiq0DixAFfPDPps/edit?usp=sharing

**Comment by ktrammell95** [comment]
Stephen,

You have some great information built out but it feels too indented. Move some text back to the left and think about other ways to make your headers stand out. Building resumes are ust like websites use styling to build a hierarchy for you. 

Look at taking the bullets off the Technologies Used and make it 3 columns, it might give you more space because I would also like to see you add some details about your projects, not too much maybe a link to how to access them on GitHub or more about them.

Also, look at how you built out your Experiences, you can use that same format for projects and it will give your resume a more unified, and cleaner look.

![Screen Shot 2019-09-26 at 10 36 38 AM](https://user-images.githubusercontent.com/10440779/65697802-934c5b00-e049-11e9-905a-a02bef960f56.png)
-------
![Screen Shot 2019-09-26 at 10 37 11 AM](https://user-images.githubusercontent.com/10440779/65697955-c989da80-e049-11e9-9dfb-a7833ec94419.png)
------
![Screen Shot 2019-09-26 at 10 38 22 AM](https://user-images.githubusercontent.com/10440779/65697962-cb539e00-e049-11e9-807f-150291f53e7d.png)
-----
